// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEIZfbEc_yXC4BUIVPZ7L2VssyKRsuKKo',
    appId: '1:1049263110641:web:4181bb0f0386f657146c50',
    messagingSenderId: '1049263110641',
    projectId: 'fir-6c871',
    authDomain: 'fir-6c871.firebaseapp.com',
    databaseURL: 'https://fir-6c871-default-rtdb.firebaseio.com',
    storageBucket: 'fir-6c871.firebasestorage.app',
    measurementId: 'G-NQCQX7VE2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVcOMNk3yyGk46-eOdTkvhdfTL9Jlu49M',
    appId: '1:1049263110641:android:517c89e8c4ad0f8c146c50',
    messagingSenderId: '1049263110641',
    projectId: 'fir-6c871',
    databaseURL: 'https://fir-6c871-default-rtdb.firebaseio.com',
    storageBucket: 'fir-6c871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQqrJYsSdFooYA0-JU4zGCnfoiqipwhQ',
    appId: '1:1049263110641:ios:7df2de371a1b9aef146c50',
    messagingSenderId: '1049263110641',
    projectId: 'fir-6c871',
    databaseURL: 'https://fir-6c871-default-rtdb.firebaseio.com',
    storageBucket: 'fir-6c871.firebasestorage.app',
    iosBundleId: 'com.example.gmailProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQqrJYsSdFooYA0-JU4zGCnfoiqipwhQ',
    appId: '1:1049263110641:ios:7df2de371a1b9aef146c50',
    messagingSenderId: '1049263110641',
    projectId: 'fir-6c871',
    databaseURL: 'https://fir-6c871-default-rtdb.firebaseio.com',
    storageBucket: 'fir-6c871.firebasestorage.app',
    iosBundleId: 'com.example.gmailProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEIZfbEc_yXC4BUIVPZ7L2VssyKRsuKKo',
    appId: '1:1049263110641:web:161465f906db0b37146c50',
    messagingSenderId: '1049263110641',
    projectId: 'fir-6c871',
    authDomain: 'fir-6c871.firebaseapp.com',
    databaseURL: 'https://fir-6c871-default-rtdb.firebaseio.com',
    storageBucket: 'fir-6c871.firebasestorage.app',
    measurementId: 'G-25WQQW17J1',
  );
}
